[package]
name = "nes-emu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
bitflags = "1.3.2"

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
test-strategy = "0.2.1"
rand = "0.8.5"
