[package]
name = "nes_emu_bus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nes_emu_cpu = { path = "../nes_emu_cpu" }
nes_emu_joypad = { path = "../nes_emu_joypad" }