[package]
name = "nes-emu-cpu-snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nes-emu-cpu = { path = "../nes-emu-cpu" }
sdl2 = "0.34.0"
rand = "=0.7.3"
