[package]
name = "nes-emu-bus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nes-emu-cpu = { path = "../nes-emu-cpu" }
nes-emu-joypad = { path = "../nes-emu-joypad" }